# Generated by Django 6.0.1 on 2026-02-03 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('gp', 'Grameenphone'), ('robi', 'Robi'), ('airtel', 'Airtel'), ('bl', 'Banglalink'), ('teletalk', 'Teletalk')], max_length=20)),
                ('sim_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('sim_pin', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
