# Generated by Django 6.0.1 on 2026-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='sim_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('root', 'Root Admin'), ('company', 'Company'), ('admin', 'Admin'), ('staff', 'Staff')], default='admin', max_length=10),
        ),
    ]
