# Generated by Django 5.2.11 on 2026-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companyprofile_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='session_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
